# hash size doc : https://www.getpagespeed.com/server-setup/nginx/tuning-nginx-maps-hashes
map_hash_bucket_size 1024;
map_hash_max_size 2048;

map $uri $redirections {
  include /etc/nginx/conf.d/legacy-to-new.map;
}

map $request_uri $redirections_docs {
  include /etc/nginx/conf.d/legacy-docs-to-new.map;
}

# agent chat transcript location map
map $upstream_http_location $agent_chat_location {
    ~^(http[s]?://[^/]+)(.*)$ $2;
}
